name: Old Comparison

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/deploy.yml'
      - 'src/**'
      - 'test/**'
      - 'action.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test-build-only:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'test/package-lock.json'
      - run: npm ci
        working-directory: ./test
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID_TESTING }}
          apiToken: ${{ secrets.CF_API_TOKEN_TESTING }}
          workingDirectory: test
          secrets: |
            SECRET1
            SECRET2
          preCommands: echo "*** pre commands ***"
          postCommands: |
            echo "*** post commands ***"
            wrangler build
            echo "******"
        env:
          SECRET1: ${{ secrets.SECRET1 }}
          SECRET2: ${{ secrets.SECRET2 }}
  test-publish:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'test/package-lock.json'
      - run: npm ci
        working-directory: ./test
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID_TESTING }}
          apiToken: ${{ secrets.CF_API_TOKEN_TESTING }}
          environment: 'production'
          workingDirectory: test
  test-publish_legacy_credentials:
    # It's legacy (unsupported) wrangler so it's problaby gonna fail
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'test/package-lock.json'
      - run: npm ci
        working-directory: ./test
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID_TESTING }}
          apiKey: ${{ secrets.CLOUDFLARE_API_KEY_TESTING }}
          email: ${{ secrets.CLOUDFLARE_EMAIL_TESTING }}
          environment: 'production'
          wranglerVersion: '1.21.0'
          workingDirectory: 'test'
  test-publish_hardcoded_wrangler_version:
    # It's legacy (unsupported) wrangler so it's problaby gonna fail
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'test/package-lock.json'
      - run: npm ci
        working-directory: ./test
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID_TESTING }}
          apiKey: ${{ secrets.CLOUDFLARE_API_KEY_TESTING }}
          email: ${{ secrets.CLOUDFLARE_EMAIL_TESTING }}
          environment: 'production'
          wranglerVersion: '1.21.0'
          workingDirectory: 'test'
  test-publish_secrets:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'test/package-lock.json'
      - run: npm ci
        working-directory: ./test
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID_TESTING }}
          apiToken: ${{ secrets.CF_API_TOKEN_TESTING }}
          environment: 'production'
          workingDirectory: test
          secrets: |
            SECRET1
            SECRET2
          preCommands: echo "*** pre command ***"
          postCommands: |
            echo "*** post commands ***"
            echo "******"
        env:
          SECRET1: ${{ secrets.SECRET1 }}
          SECRET2: ${{ secrets.SECRET2 }}